### PR TITLE
Expose ShipInfo::augList

### PR DESCRIPTION
**Pull request by Choosechee**
There's no way to check the hidden augments of a ship in Lua right now. Exposing CustomAugmentManager would provide the method GetShipAugments, which would hopefully allow you to check them. IsAugment could also be a useful method for adding cross compatibility with addons.

### CODE REVIEW

**Comment by Nasa62** [comment]
Please add the corresponding documentation entry in the wiki files (wiki folder)

**Comment by Choosechee** [comment]
> Please add the corresponding documentation entry in the wiki files (wiki folder)

Done.

**Review by Nasa62 — DISMISSED** [review]

**Comment by Choosechee** [comment]
I noticed this line in hyperspace.i:
`%template(unordered_map_string_int) unordered_map<string,int>; // line 126`
(I added the comment with the line number). Shouldn't this template be the one that hiddenAugs needs? Why didn't it work when I tested it? Is hiddenAugs an ordered map?

**Review by ChronoVortex — CHANGES_REQUESTED** [review]
Checking the code, it doesn't look like `ShipManager_Extend::hiddenAugs` is even referenced anywhere after it's declared, so it's probably not what you want. Try `CustomAugmentManager::GetShipAugments`, that one might return a list that includes the hidden augments.

**Review by ChronoVortex — APPROVED** [review]
It turns out that it was impossible to distinguish between hidden augments and normal augments in the list returned by `GetShipAugments`. The only place I could find where they are distinguishable is `ShipInfo::augList`, where hidden augments have the `HIDDEN` prefix. You can get all the augments for the player ship with this code:
```lua
local augs = Hyperspace.Global.GetInstance():GetShipInfo(false).augList:keys()
```
`augs` will be a `vector` containing all the augments on the ship. Using this on the MV Kestrel at the start of the game, for example, gives this list:
```
FTL_JUMPER_SCANNER    
HIDDEN FOR_MULTIVERSE    
HIDDEN MIND_ORDER    
HIDDEN SHIP_MULTIVERSE    
```

**Pull request merged**
