### PR TITLE
1.3.0

### PR DESCRIPTION
**Pull request by Nasa62**
1.3.0 Release with many backwards-compatible changes.

##### Changes

- Linux: fixed crash on ship stats page
- Windows: Fixed locale issues from message boxes on Windows (i.e. no bajimoke messages)
   - Note: if you're calling message boxes from lua files, they should be encoded in UTF-8.
- Windows: Error messages now appear in front of the game window.
- Additional LUA enhancements and exposed functionality
- Added lowHealthThreshold and lowHealthThresholdPercentage for custom races to change the health value at which beeping sound plays and health bar flashes red.
- Super shield drones now load the image specified in their blueprint instead of the default for all super shield drones.
- XML data can now be read by LUA.
- Cross-platform docker build support for development
- Added `iconReplace` tag for weapons
- Thruster animations now render under the floor image instead of above
- Beams with a length of 1 are forced to target a single room tile (this one is vert's, not mine)
- Added `SHIP` prefix for event `reqs` and `HasEquipment`
- Fixed teleport-move crew getting stuck on the enemy ship after a fight if they have the energy shield augmentation.
- Sector quests can now work with no req.
- Can no longer teleport-move from own ship to neutral enemy ship.
- Adjusted timing of teleport movement in the code so that the player cannot teleport-move onto an enemy ship with cloaking right at the start of the fight.
- Added new custom req keywords:
  - ACH: Precedes the name of an achievement to check, e.g. "ACH FOO".
  - ITEM: Forces an exact item check, ignores augment functions, ignores custom reqs, hidden augments are separate, blueprint lists can still be used. Used for setting prerequisites for events that actually consume an item/augment rather than using its function. For example "ITEM ADV_SCANNERS" or "ITEM HIDDEN ADV_SCANNERS".
  - dlc: Checks whether AE is enabled.
  - hull: Checks remaining player hull.
- Player variables and metavariables are exposed to lua.
- Internal event callbacks can now take an additional argument which specifies their priority. Higher number priority runs first. If not provided then default is 0.
- Added lots of new callbacks, callback functionality, callback priorities (as an extra optional argument, default 0, higher numbers come first). Please refer to the lua-related Hyperspace source code for a list.
- Room stat boost durations are now affected by the temporal manipulator.
- roomAnim can now have a wallAnim.
- Fixed system power bar rendering issues.
- Completed erosion.
- Block time from advancing while the game is loading.
- Render events can be chained as with internal events and support nesting.
- Fixed bugs with charge abilities where the game would hang under certain conditions.
- Added customization for CrewBox; will be exposed to lua in the future.
- A number of changes to crew abilities and ability-related stat boosts, including crew being able to have multiple abilities (WIP feature, please see xml).
- Fixed rendering statboosts on dead crew.
- Fixed recallBoarders not recalling dying crew
- Fixed initial player variables being seeded incorrectly at the start of the run.

### CODE REVIEW

**Comment by mathchamp93** [comment]
Change summary:

- Fixed teleport-move crew getting stuck on the enemy ship after a fight if they have the energy shield augmentation.
- Sector quests can now work with no req.
- Can no longer teleport-move from own ship to neutral enemy ship.
- Adjusted timing of teleport movement in the code so that the player cannot teleport-move onto an enemy ship with cloaking right at the start of the fight.
- Added new custom req keywords:
- - ACH: Precedes the name of an achievement to check, e.g. "ACH FOO".
- - ITEM: Forces an exact item check, ignores augment functions, ignores custom reqs, hidden augments are separate, blueprint lists can still be used. Used for setting prerequisites for events that actually consume an item/augment rather than using its function. For example "ITEM ADV_SCANNERS" or "ITEM HIDDEN ADV_SCANNERS".
- - SHIP: Checks the ship blueprint name.
- -dlc: Checks whether AE is enabled.
- -hull: Checks remaining player hull.
- Player variables and metavariables are exposed to lua.
- More stuff exposed in lua in general.
- Internal event callbacks can now take an additional argument which specifies their priority. Higher number priority runs first. If not provided then default is 0.
- Added lots of new callbacks, callback functionality, callback priorities (as an extra optional argument, default 0, higher numbers come first). Please refer to the lua-related Hyperspace source code for a list.
- Room stat boost durations are now affected by the temporal manipulator.
- roomAnim can now have a wallAnim.
- Fixed system power bar rendering issues.
- Completed erosion.
- Block time from advancing while the game is loading.
- Render events can be chained as with internal events and support nesting.
- Fixed bugs with charge abilities where the game would hang under certain conditions.
- Added customization for CrewBox; will be exposed to lua in the future.
- A number of changes to crew abilities and ability-related stat boosts, including crew being able to have multiple abilities (WIP feature, please see xml).
- Fixed rendering statboosts on dead crew.
- Fixed recallBoarders not recalling dying crew
- Fixed initial player variables being seeded incorrectly at the start of the run.
- Additional updates to German translation.
- Added devcontainer build, using Docker. Developers can easily build for all targets now. Code::Blocks build is deprecated but will remain supported for now.
- Beam weapons with a length of 1 (pinpoint) now target on individual tiles rather than like normal beams. Pinpoint beams will also display a "pinpoint" text rather than the beam length (todo: add translations).
- The sound that plays when dismissing crew can now be changed or disabled.
- Ship best stats page should no longer crash in linux.
- Thrusters now render underneath the floor image.
- Added <iconReplace> for weapon blueprints. This should be a single frame animation that will replace the weapon's normal icon for rendering in the equipment, store, or hangar screen. Can be used to make a mini icon for a large weapon.

**Review by mathchamp93 — COMMENTED** [review]
It's not really practical for me to fully review and test every single change but I've posted a release candidate on the MV discord and I've checked that it works on my end (at least that I can do basic things such as load the game with the Multiverse mod, start a run, continue a saved run, and that it hasn't cooked my profile). I've also gone through the list of commits to see what was added/changed at a high level.

I've also made a couple of minor commits since then (only some slight lua and documentation changes). If nobody reports any major issues within the next few days then we can merge.

**Comment by ChronoVortex** [comment]
I'd still like an XML parser added, but at the very least I'd like the most recent PRs into develop that are open right now to be merged before 1.3. There are only 4 and most of the review they need has already been done.

**Comment by ChronoVortex** [comment]
Few new release notes:
- Added lowHealthThreshold and lowHealthThresholdPercentage for custom races to change the health value at which beeping sound plays and health bar flashes red
- Super shield drones now load the image specified in their blueprint instead of the default for all super shield drones 
- Error messages now appear in front of the game window
- XML data can now be read by LUA

**Pull request merged**
