### PR TITLE
stuff for dynamic resist and system limits

### PR DESCRIPTION
**Pull request by ChronoVortex**
- Add `SHIP_LOOP` callback, better for `ON_TICK` for code that shouldn't run while the game is paused
- Add render callbacks
- Expose `ShipSystem_Extend::additionalPowerLoss` to LUA

### CODE REVIEW

**Comment by Nasa62** [comment]
Description/Explanation/Sample Code/Something?

**Comment by ChronoVortex** [comment]
Implemented in Vertex
https://github.com/ChronoVortex/FTL-HS-Vertex/blob/feature/limitEffect/data/vertex_module/tags/limitEffects.lua

**Comment by Nasa62** [comment]
What new render callbacks, guess I need to update the wiki or we need a place for the wiki better than GitHub

**Comment by ChronoVortex** [comment]
You can see the new callbacks in the RenderEvents header
<https://github.com/FTL-Hyperspace/FTL-Hyperspace/pull/93/files#diff-4437fc9cd33c764b0a9a9cbb61b996b65ef07146e28f33e44dee78fff195754c>

**Review by Nasa62 — APPROVED** [review]
@ChronoVortex you can add stuff to the wiki now, so add the stuff to the wiki before or when you merge this :)

I'll leave it unmerged for you to do that.

**Pull request merged**
